In [1]:
import torch
a = torch.ones(3)  # default dtype=torch.float
print(a)

# the min unit of a tensor is a tensor
print(a[1])
print(float(a[1]))

tensor([1., 1., 1.])
tensor(1.)
1.0


In [2]:
torch.zeros(3, 2).shape

torch.Size([3, 2])

In [3]:
rand3_2 = torch.rand(3, 2)
print(rand3_2.storage(), 
      rand3_2.storage()[1], sep='\n')

 0.4941365122795105
 0.6145930290222168
 0.7663203477859497
 0.4274972081184387
 0.5633124113082886
 0.7500499486923218
[torch.FloatStorage of size 6]
0.6145930290222168


In [4]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)
points_t = points.t()   # transpose
print(points_t)
id(points.storage()) == id(points_t.storage())

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[4., 5., 2.],
        [1., 3., 1.]])


True

In [5]:
# PyTorch tensors can be converted to NumPy arrays
points = torch.ones(4, 3)
points_np = points.numpy()
points_np

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [6]:
# vice versa
import numpy as np
arr_np = np.array([3, 2, 1])
arr = torch.from_numpy(arr_np)
arr

tensor([3, 2, 1], dtype=torch.int32)

In [7]:
# Serializing tensor
print(points)
filename = "../data/ch3/points.t"

# torch.save(points, filename)
with open(filename, "wb") as f:
    torch.save(points, f)

# Deserializing
# points = torch.load(filename)
with open(filename, "rb") as f:
    points = torch.load(f)

print(points)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [18]:
# $ conda install h5py
import h5py

with h5py.File("../data/ch3/points.hdf5", "w") as f:
    dset = f.create_dataset("coords", data=points.numpy())

with h5py.File("../data/ch3/points.hdf5", "r") as f:
    dset = f['coords']
    last_points = torch.from_numpy(dset[-2:])
print(last_points)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [21]:
# Moving tensors to the GPU

'''
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

points_gpu = points.to(device='cuda')

points_gpu = points.cuda()
'''

# ran on Google Colab

"\npoints_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')\n\npoints_gpu = points.to(device='cuda')\n\npoints_gpu = points.cuda()\n"