In [1]:
import torch
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [2]:
a.size()

torch.Size([9])

In [3]:
a[2].storage_offset()

2

In [4]:
a.stride()

(1,)

In [5]:
b = a.view(3, 3)   # reshape tensor `a` into (3, 3) (aka change the value of stride)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
id(a.storage()) == id(b.storage())

True

In [8]:
torch.sqrt(b.double())

tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361],
        [2.4495, 2.6458, 2.8284]], dtype=torch.float64)

In [9]:
torch.cos(b.double())

tensor([[ 1.0000,  0.5403, -0.4161],
        [-0.9900, -0.6536,  0.2837],
        [ 0.9602,  0.7539, -0.1455]], dtype=torch.float64)